Add functionality to create, look up, edit and delete notes
ib-ua/_bot pull request #1
Opened 2023-12-16 13:56 UTC by HelHeim111

2023-12-16 14:18 UTC, ib-ua requested changes

2023-12-16 14:18 UTC, ib-ua commented on notes_book.py
> +from note import Note
Imported but never used

2023-12-16 14:18 UTC, ib-ua commented on notes_book.py
> +class Note_book:
class name doesn't match code convention

2023-12-16 14:18 UTC, ib-ua commented on notes_book.py
> +    @notes.setter
names of the function and decorator don't match

2023-12-16 14:18 UTC, ib-ua commented on notes_book.py
> +            self._notes = notes
prefix private fields with double _ character

2023-12-16 14:18 UTC, ib-ua commented on note.py
> +class Note:
The class Note migth be descendants from Field

2023-12-16 14:18 UTC, ib-ua commented on notes_book.py
> +            return []
It doesn't make sense to return an empty list in case of reading notes for an unknown user

2023-12-18 20:39 UTC, ib-ua approved these changes

2023-12-18 20:40 UTC, Flairim approved these changes

2023-12-18 20:40 UTC, merged